package registry

type registry struct {
	postMongoRepositoryRegistry
	postMysqlRepositoryRegistry
	postRedisRepositoryRegistry
	commentMongoRepositoryRegistry
	commentMysqlRepositoryRegistry
	commentRedisRepositoryRegistry
}
